// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARjQCKIhT-hagi4pSun5oAwi0QfQPU3NE',
    appId: '1:381554916446:web:577402742a0cb3f61248cf',
    messagingSenderId: '381554916446',
    projectId: 'aquaintel-36924',
    authDomain: 'aquaintel-36924.firebaseapp.com',
    storageBucket: 'aquaintel-36924.firebasestorage.app',
    measurementId: 'G-M0G5CF1PBX',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuGTkawrjYA7l8B6D7DS7vek6gUItca3M',
    appId: '1:381554916446:ios:9acc6db5219e5a201248cf',
    messagingSenderId: '381554916446',
    projectId: 'aquaintel-36924',
    storageBucket: 'aquaintel-36924.firebasestorage.app',
    iosBundleId: 'com.example.aquaintel',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuGTkawrjYA7l8B6D7DS7vek6gUItca3M',
    appId: '1:381554916446:ios:9acc6db5219e5a201248cf',
    messagingSenderId: '381554916446',
    projectId: 'aquaintel-36924',
    storageBucket: 'aquaintel-36924.firebasestorage.app',
    iosBundleId: 'com.example.aquaintel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARjQCKIhT-hagi4pSun5oAwi0QfQPU3NE',
    appId: '1:381554916446:web:1bcde404f718d2a81248cf',
    messagingSenderId: '381554916446',
    projectId: 'aquaintel-36924',
    authDomain: 'aquaintel-36924.firebaseapp.com',
    storageBucket: 'aquaintel-36924.firebasestorage.app',
    measurementId: 'G-601P3HM0DK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDND6onaVyLIGrhL_gAGWejQ0x8e0YKydY',
    appId: '1:381554916446:android:2d989b9e5191c4ad1248cf',
    messagingSenderId: '381554916446',
    projectId: 'aquaintel-36924',
    storageBucket: 'aquaintel-36924.firebasestorage.app',
  );
}
